global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]

  - job_name: "novawallet-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5000"]
