apiVersion: v1
kind: ConfigMap
metadata:
  name: novawallet-api-config
  namespace: novawallet
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  OBSERVABILITY__OPENTELEMETRY__ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
