apiVersion: v1
kind: Secret
metadata:
  name: novawallet-api-secrets
  namespace: novawallet
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=NovaWalletDb;User Id=sa;Password=NovaWallet!2345;TrustServerCertificate=True;Encrypt=False;"
  JwtSettings__Issuer: "novawallet"
  JwtSettings__Audience: "novawallet"
  JwtSettings__SecretKey: "CHANGE_ME_32_CHAR_SECRET_KEY_123456"
